services:
  - type: web
    name: lottery-insights
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: R_MAX_NUM_DLLS
        value: 150

