run_as shiny;

# Control number of worker processes (default is 3)
simple_scheduler 15;

# Prevent one worker from hogging too many connections
max_conns_per_process 20;

server {
  listen 3838;

  # Close idle sessions after 2 minutes
  app_idle_timeout 120;
  
  # This keeps websocket connections fresh and reduces Cloudflare disconnects.
  heartbeat_rate 120;

  location / {
    app_dir /srv/shiny-server/;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}