run_as shiny;

# Only 1-2 worker processes for limited resources
simple_scheduler 1;

# Limit connections per process
max_conns_per_process 5;

server {
  listen 3838;
  
  # Close idle sessions after 2 minutes
  app_idle_timeout 120;
  
  # This keeps websocket connections fresh and reduces Cloudflare disconnects.
  heartbeat_rate 120;

  location / {
    app_dir /srv/shiny-server/;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}